export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_TODO_LIST_START = 'FETCH_TODO_LIST_START';
export const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS';
export const FETCH_TODO_LIST_ERROR = 'FETCH_TODO_LIST_ERROR';
export const FETCH_TODO_STATUS = 'FETCH_TODO_STATUS';
export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const IN_ARCHIVE_TODO_START = 'IN_ARCHIVE_TODO_START';
export const IN_ARCHIVE_TODO_SUCCESS = 'IN_ARCHIVE_TODO_SUCCESS';
export const IN_ARCHIVE_TODO_ERROR = 'IN_ARCHIVE_TODO_ERROR';