# Generated by Django 3.1.2 on 2020-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20201028_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='in_archive',
            field=models.BooleanField(default=False),
        ),
    ]
