# Generated by Django 3.1.2 on 2020-11-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todo_in_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todolist.todo'),
        ),
    ]
